### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [feibl/search-rex#1]
What would be the license for your fine code?

**Comment by feibl** [comment]
Hallo Stefan,

Was denkst du, was für eine Lizenz sollte für den Code vergeben werden?

Gruss,
Fabian

-------- Original message --------

**Comment by feibl** [comment]
I'm sorry. I tried to redirect the mail to my advisor, but instead I sent a response :)

Coming back to the license, I first have to ask my advisor, as the code was developped parallel to my master thesis. I will be able to respond as soon as I receive an answer.

**Comment by feibl** [comment]
The MIT-license is useed for this code. It can be seen in the LICENSE.md file

**Comment by pombredanne** [comment]
Thanks for fixing this so quickly.! :+1:

**Comment by feibl** [comment]
You're welcome

-------- Original message --------
